services:
  localdb:
    image: postgres:15.1
    ports:
      - "5432:5432"
    volumes:
      - ./db/dumps:/app-db-dumps
    environment:
      - POSTGRES_USER=jonathasmarques04
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=jonathasProduction

  testdb:
    image: postgres:15.1
    ports:
      - "5433:5432"
    volumes:
      - ./db/dumps:/app-db-dumps
    environment:
      - POSTGRES_USER=jonathasmarques04
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=jonathasTest